### ISSUE TITLE
[1pt] Navigation pannel

### ISSUE THREAD

**Issue by paulinagonzalezc** [Nelitaa/book-an-appointment-back-end#12]
* Motorcycles/doctors/classes/items that you selected as a theme.
* "Reserve" form.
* "My reservations".
* "Add motorcycle/doctor/class/item that you selected as a theme" (the link is visible to everybody).
* "Delete motorcycle/doctor/class/item that you selected as a theme" (the link is visible to everybody).

**Comment by Nelitaa** [comment]
[PR](https://github.com/emmanuellmhango/book-an-appointment/pull/2)
