### ISSUE TITLE
[2pt] Reservation form page(button in details page)

### ISSUE THREAD

**Issue by paulinagonzalezc** [Nelitaa/book-an-appointment-back-end#16]
Connect to reservations endpoint

**Comment by Nelitaa** [comment]
This is the PR for the reservations form page [PR](https://github.com/emmanuellmhango/book-an-appointment/pull/10), but we have too many conflicts until the merge. Is for that reason that we added the reservations logic fixed and made it work with the doctor's logic in this another [PR](https://github.com/emmanuellmhango/book-an-appointment/pull/11)
